export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};
export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <main>{children}</main>
      </body>
    </html>
  );
}
