import Sidebar from "@/app/components/navigation/sidebar/sidebar";
import QueryProvider from "@/lib/queryProvider/queryProvider";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function DashboardLayout({ children }) {
  return (
    <>
      <QueryProvider>
        <Sidebar />
        <main className="min-h-screen mt-12 ml-0 md:ml-60 mr-5 lg:mr-10 mb-20">
          {children}
        </main>
      </QueryProvider>
    </>
  );
}
