import BackToTop from "./components/navigation/backToTop/backToTop";
import StickyNavbar from "./components/navigation/sticky/stickyNavbar";
import "./globals.css";
import Footer from "./sections/common/footer/footer";
import Partners from "./sections/common/partners/partners";
export const metadata = {
  title: "Khan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <header>
          <StickyNavbar />
        </header>
        <main className="">
          {children}
          <BackToTop />
          <Partners />
          <Footer />
        </main>
      </body>
    </html>
  );
}
