import StickyNavbar from "./components/navigation/sticky/stickyNavbar";
import BackToTop from "./components/navigation/backToTop/backToTop";
import AuthProvider from "@/lib/authProvider/authProvider";
import { MdReportGmailerrorred } from "react-icons/md";
import Footer from "./sections/common/footer/footer";
import { GiPartyPopper } from "react-icons/gi";
import { ImWarning } from "react-icons/im";
import { Toaster } from "sonner";
import "./globals.css";
import Preloader from "./components/preloader/preloader";

export const metadata = {
  title: "Khan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <Toaster
          className="bg-slate-50 max-w-xs text-wrap"
          icons={{
            success: <GiPartyPopper className="text-green-500 text-2xl mr-2" />,
            error: (
              <MdReportGmailerrorred className="text-red-500 text-2xl mr-2" />
            ),
            warning: <ImWarning className="text-yellow-500 text-2xl mr-2" />,
          }}
          toastOptions={{
            descriptionClassName: `ml-1 text-[.6rem] font-semibold`,
            className: `w-fit border border-slate-300`,
          }}
          position="top-center"
          richColors
        />
        <AuthProvider>
          <Preloader>
            <header>
              <StickyNavbar />
            </header>
            <main className="">{children}</main>
            <Footer />
            <BackToTop />
          </Preloader>
        </AuthProvider>
      </body>
    </html>
  );
}
